### PR TITLE
bump go version from 1.12 to 1.20

### PR DESCRIPTION
**Pull request by microyahoo**
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>

### CODE REVIEW

**Comment by microyahoo** [comment]
hi @mulbc, PTAL, thanks.

**Comment by mulbc** [comment]
why not go with 1.20 while we're at it?

**Comment by microyahoo** [comment]
> why not go with 1.20 while we're at it?

done

**Comment by mulbc** [comment]
thanks

**Pull request merged**
